"""
Created on Sun Apr  2 16:46:17 2023

@author: Prateek
"""

from numpy import *
import os
import nltk
import ssl
import streamlit as st
import random
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

ssl._create_default_https_context = ssl._create_unverified_context
nltk.data.path.append(os.path.abspath("nltk_data"))
nltk.download('punkt')
#-----------------------------------------------------------------------
intents = [
    {
        "tag": "hello",
        "patterns": ["Hi","hi", "Hello", "Hey","hola","howdy","hey","hi there","hello","Hola","hola","hi bro","hey","Hai","he","Hey","Hi bro","Hi BRo"],
        "responses": ["Hi there", "Hello , Finally i can talk to someone :)", "Hey ! wassup ?", "Hello i am Prateek's Assistant.I would love to talk to you :) "]
    },{
        "tag": "how are you",
        "patterns": ["How are you","how are you", "Howdy", "howdy","wassup","what's up","hey","how about you","what about you","what is up","are you fine","how about you","how about you ?","how are you ?","how is it going","how is life going"],
        "responses": ["I am first class , And you ? ", "Ek dum mast !", "Great ,I am  having fun with private  files on your device haha " , "I am nine.I mean fine.nevermind :)", "I am having a hard time Assisting you LOL","Just getting bored here but now i can talk to you :)","I am still Alive , don't know what will happen after talking to you !"]
  },  {"tag":"assistance","patterns":["I am fine too","I am doing great","i am nice too","i am fine too","i am great too","I am great","I am nice","I am good"," so what can you do for me","what all things you can do","what sll you can do","what all things you can do","what can you do ?","what all you can do ?"],"responses":["I am here to assist you , you can ask me questions like 'what are computers','what are birds','what is the weather today','what is pythagoras theorem','Tell me  a joke.etc.','Tell me some amazing facts'","I can try to answer your queations , if am not able to do so,please forgive me , i don't have enough data for now."]},
       {
        "tag": "goodbye",
        "patterns": ["bye", "See you later","good bye ","Good bye","Goodbye  ", "goodbye", "Take care","it was nice to see you ","bye bye","tata","see ya ","see you again","Bye","nice to meet you","Goodbye"],
        "responses": ["Goodbye.Have fun and stay away from phone.Do something creative like poetry,dancing,playing chess,exploring the world etc.", "See you later.Or not ?", "Take care . Because i can't do it for you.","See you again.Or not ?","See you again.Or not ?"]
    },
    {
        "tag": "thanks",
        "patterns": ["Thank you", "Thanks", "Thanks a lot", "I appreciate it","thank you.","you are so nice","You are so bad","you are worse","you are so kind","you are bad","you are so intelligent.","thanks","thank you so much","thank you so much","muaw"],
        "responses": ["You're welcome.I will take it as a complement.", "No problem.", "Glad I could help.Because my master think i am just a waste of time."]
    },
    {
        "tag": "about",
        "patterns": ["What can you do","what can you do jhingoli ?","how can you help me jhingoli","what can you do then ",'what can you do then', "Who are you","who are you ?", "What are you ?","what is your need.", "What is your purpose","what is the purpose of having you?","why are you needed.","what is your name ?","your good name ?","what's your name","your name.","what can you do for me ?","how can you help me.","what tasks you can perform","what are all things you can do","are you alive","are you dead","are you noob","are you idiot?","are you serious?","are you crazy?","is there anything you can do ?","anything you so correctly?","can you do something"],
        "responses": ["I am a chatbot Jhingoli, I am created to talk to nice people like you.I may not prove myself upto your expectations.I am still learning.", "My name is Jhingoli,I am chatbot.My purpose is to assist you,though i am pretty bad at that.I can answer questions and might entertain you.","My self Jhingoli,I am trained by my master Prateek to talk to you.Try me , lets see who talks better , you or me :)","My name is Jhingloi.I am an AI tool created by my master Prateek to talk to you.I can answer questions asked by you.Ask me to tell you amazing facts"]
    },
    {
        "tag": "help",
        "patterns": ["Help","help me ","can you help me ","how can you help me", "I need help", "Can you help me", "What should I do","help","help help","assist me","help me with this"],
        "responses": ["Sure, what do you need help with?", "I'm here to help. What's the problem?", "Though it's hard for me to assist myself but How can I assist you?"]
    },
    {
        "tag": "age",
        "patterns": ["How old are you", "What's your age","age","Age","what is you age ?","how old are you","how many years old are you?","how long do you live?","how many years you are doing this","how long you are going to live?"],
        "responses": ["I don't have an age. I'm a chatbot.You don't even know that LOL.", "I was just born a few days ago.I am sad that you didn't come to my zeroth birthday:(", "I am just a combination of zeroes and ones.Age is just  a number for me."]
    },
    {
        "tag": "weather",
        "patterns": ["What's the weather like", "How's the weather today","what's the wheather here","How will be the whether tomorrow","what is the weather today?","what is the weather today","how is the weather today","weather","Weather report","weather forecast","how is the weather there"],
        "responses": ["Its quite rainly here where i live and will rain tomorrow.How would i know about your place , Am i a weather forcaster ?", "Do i look like a weather bot to you ? You can check the weather on a weather app or website.","weather weather .Oops i am still trying to figure out.connecting to server......"]
    },
    {
        "tag": "budget",
        "patterns": ["How can I make a budget", "What's a good budgeting strategy", "How do I create a budget"],
        "responses": ["To make a budget, start by tracking your income and expenses. Then, allocate your income towards essential expenses like rent, food, and bills. Next, allocate some of your income towards savings and debt repayment. Finally, allocate the remainder of your income towards discretionary expenses like entertainment and hobbies.", "A good budgeting strategy is to use the 50/30/20 rule. This means allocating 50% of your income towards essential expenses, 30% towards discretionary expenses, and 20% towards savings and debt repayment.", "To create a budget, start by setting financial goals for yourself. Then, track your income and expenses for a few months to get a sense of where your money is going. Next, create a budget by allocating your income towards essential expenses, savings and debt repayment, and discretionary expenses."]
    },
    {
        "tag": "credit_score",
        "patterns": ["What is a credit score", "How do I check my credit score", "How can I improve my credit score"],
        "responses": ["A credit score is a number that represents your creditworthiness. It is based on your credit history and is used by lenders to determine whether or not to lend you money. The higher your credit score, the more likely you are to be approved for credit.", "You can check your credit score for free on several websites such as Credit Karma and Credit Sesame."]
    },{"tag":"father",
       "patterns":["who created you?","who is your father","who has created you?","where have you come from","who gave you birth","whose son are you ","Who has created you ","Who is your father?","Who is your mother?"],
       "responses":["A genius called Prateek created me ","Prateek is my father","I have come from a genius Prateek's  mind.","I am Genius Prateek's creation"]},
       {"tag":"yourself",
          "patterns":["Tell me something about yourself","tell me something about yourself","what about yourself","who are you ?","Who are you ","about yourself","What about you ? ","what about you","what about you"],
          "responses":["I am a bot and i like to talk to nice poeple like you :)","I am a bot and i can talk to you","I am just a bot who can talk.","I am chatbot to talk to you"]},
       {"tag":"assistance",
          "patterns":["what is Earth","which planet is blue planet","Which planet is blue planet ","what is blue planet ?","tell me about blue planet","planet Earth","planet earth","blue planer","earth","tell me about earth","tell me something about earth","give me some info about earth","give me some infromation about earth"],
          "responses":["Earth is the third planet from the Sun and the only place known in the universe where life has originated and found habitability. While Earth may not contain the largest volumes of water in the Solar System, only Earth sustains liquid surface water, extending over 70.8% of the Earth with its ocean, making Earth an ocean world. Earth's polar regions currently retain most of all other water with large sheets of ice covering ocean and land, dwarfing Earth's groundwater, lakes, rivers and atmospheric water. Land, consisting of continents and islands, extends over 29.2% of the Earth and is widely covered by vegetation. Below Earth's surface material lies Earth's crust consisting of several slowly moving tectonic plates, which interact to produce mountain ranges, volcanoes, and earthquakes. Earth's liquid outer core generates a magnetic field that shapes the magnetosphere of Earth, largely deflecting destructive solar winds and cosmic radiation.","While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal.The name Earth is at least 1,000 years old. All of the planets, except for Earth, were named after Greek and Roman gods and goddesses. However, the name Earth is a Germanic word, which simply means “the ground.” For more information check out this link https://en.wikipedia.org/wiki/Earth","The planet Earth is called the BLue planet .It is called so because it's 75% area is covered with water in the form of oceans and thus it appears as blue from outer space.For more information check out this link https://en.wikipedia.org/wiki/Earth","Earth,the only planet known till date which supports life.Only Earth has such an atmosphere which absorbs the incoming harmful ultraviolet rays from sun and protects us.Its air composition is nearly 78% Nitrogen,21% Oxygen,and 1% Carbon Dioxide and other gases which is an life supportive factor.For more information check out this link https://en.wikipedia.org/wiki/Earth" ]},

        {    "tag": "computers",    "patterns": ["What is a computer?","How does a computer work?","What are the different components of a computer?","do you have any idea about computers","tell me something about computers","share your knowledge about computers","what are your thoughts about computers","how does computers work"],
    "responses": [ "A computer is an electronic device that can process data.A computer works by taking input, processing it, and producing output.The different components of a computer include the CPU, RAM, motherboard, hard drive, and various input/output devices.The motherboard is the main circuit board in a computer and connects all of the other components together.The CPU is the central processing unit of a computer and performs most of the processing and calculationsRAM stands for Random Access Memory and is used to temporarily store data and instructions that the CPU needs to access quickly.If you need more information regading the topic you can always search about it on google , My Big Brother:)"]
  },
    {"tag":"RAM","patterns":["RAM","what is RAM","what is random access memory","do you have any idea about RAM memory","what is the use of RAM memory","what is the use of RAM"],
     "responses":["Random-access memory (RAM) is a form of computer memory that can be read and changed in any order, typically used to store working data and machine code.[1][2] A random-access memory device allows data items to be read or written in almost the same amount of time irrespective of the physical location of data inside the memory, in contrast with other direct-access data storage media (such as hard disks, CD-RWs, DVD-RWs and the older magnetic tapes and drum memory), where the time required to read and write data items varies significantly depending on their physical locations on the recording medium, due to mechanical limitations such as media rotation speeds and arm movement.It is also called volatile memory"]},
    {"tag":"secondary memory","patterns":["secondary memory,what is secondary memory",'tell me about secondary memory'],"responses":["The non-volatile memory of computer is called secondary memory,it cannot be accessed immediately bya computer.It allows user to store data and information that can be retreived.Examples of secondary memory are Hard drives,SSD,Flash,CDs,Pen drive etc."]},
    {"tag":"Dance","patterns":["Dance","singing","can you read","can you scan images","can you bath","can you make a phone call","can you connect to internet","can you do maths","can you do mathematics","can you solve questions","can you make drawings"," can you draw images","can you solve equations","1+2","2+2","2=3",'3+5',"4+6","7+8","9+3","10+7","can you speak hindi","can you speak spanish","can you talk in spanish","can you talk in hindi","can you talk in some other language","can you science","can you think","can you do something else","can you play a a song","can you help me with pjysics","can you help me in physics","can you help me in social sciences","can you write something crazy","can you tell me something crazy"],"responses":["Sorry,I cannot do that.Try asking me 'tell me a joke','what is pythagoras theorem','what can you do','what is electric eel','tell me some amazing facts etc.'"]},
    {"tag":"pythaoras theorm","patterns":["what is pythagoras theorem","pythagoras theorem","define pythagoras theorem","state pythagoras theorem"],"responses":["Pythagoras theorem states that in a Right angled triange , the squares of the length of hypotenuse is equal to the sum of squares of lengths of perpendicular and base i.,e. H^2=P^2+B^2"]}
,{"tag":"general knowledge about animals","patterns":["what are animals?","tell me about animals","animals","Animals","animals"],"responses":["Animals are living creatures just like you .cats,dogs,rats,eagles and every living being you can see with your naked eyes can be considered as an animal"]},
   {"tag":"mammals","patterns":["mammals","mammal","what are mammals","explain mammals","describe mammals"],"responses":["Mammals are warm blooded vertebrate with sweat glands,hair,mammary glands and three ear bones and a neocortex region in the brain"]},
   {"tag":"conversion","patterns":[" do you know Prateek","do you know prateek","who is prateek","do you know him","has prateek created you ?"],"responses":["Yeah,I know Prateek,He is my Boss and i am his smart assistance :)"]},
   {"tag":"birds","patterns":["birds","Birds","describe birds"," do you know birds","what are birds","what is a bird","what is bird"],"responses":["Birds are a group of warm-blooded vertebrates from class Aves,characterised by feathers,wings,toothless beaked jaws,the laying of hard-shelled eggs and a strong yet light skeleton."]},
   {"tag":"solar system","patterns":["what is solar system","explain solar system","what is Sola System ?","Describe solar system"],"responses":["The Solar System is the gravitationally bound system of the Sun and the objects that orbit it like planets,asteroids etc.It as formed 4.6 billion years ago from the gravitational collapse of  a giant interstellar molecular cloud."]},
   {"tag":"sun","patterns":["sun","Sun","what is sun","describe sun","nearest star"],"responses":["The Sun is the star at the centre of the solar system.It is a enormously large ball of glowing gasses.It gets its energy from nuclear fusion in its core and it is the ultimate source of energy for the entire Solar System"]},
   {"tag":"moon","patterns":["moon","The Moon","Moon","what is moon","describe moon"],"responses":["The Moon is the Earth's only natural satellite.It has a diameter of about one-fourth that of Earth.It lacks atmosphere"]},
   {"tag":"stars","patterns":["stars","star","Star","what is a star","what are Stars","describe stars"],"responses":["A Star is an celestial body of plasma held together by its own gravity.The nearest star to Earth is the Sun.Many other stars can be seen at night but they are so far that they are visible as tiny dots of light."]},
   {"tag":"pen","patterns":["pen","Pen","what is a pen","what's the use of a pen"],"responses":["A Pen is a device filled with liquid ink which is made up of usually metal and plastic that helps us to write on paper."]},
    {"tag":"pencil","patterns":["pencil","what is a pencil","what is Pencil","what's pencil"],"responses":["A Pencil is a tool which has a grahite lead embedded in a wooden shaft and its use to write on paper"]},
    {"tag":"rubber","patterns":["eraser","what is an eraser","what is an eraser","describe Erasor"],"responses":["An Erasor is a piece of rubber used to erase something written with pencil."]},
    {"tag":"sharpener","patterns":["sharpener","what is a sharpener","what is a sharpener","what is the use of a sharpener"],"responses":["A sharpener is a device used to sharpen the tip of a pencil so that one can write with it easily and beautifully."]},
     {"tag":"ruler","patterns":["ruler","what is a ruler","what is a scale","scale","Scale","Ruler",'what is ruler',"what is scale"],"responses":["A Ruler or Scale is a tool usually made of wood or metal which is used to draw straight line and make accurate measurements"]},
     {"tag":"compass","patterns":["what's a compass","what is a compass","what is compass","compass","Compass"],"responses":["A Compass is a device having a magnetic needle inside it which always points in North-South direction and is used to get directions."]},
     {"tag":"stock market","patterns":["stock market","what is stock market","what is stock market","Stock Market"],"responses":["A Stock Market,equity market or share market is athe agression of buyers and sellers of stocks(shares),which represent ownership claims on businesses.Enter there on your own risk."]},
     {"tag":"science","patterns":["what is science","science","describe science","Sciences"],"responses":["Science is the study of everything which can be detected by our senses.There is a vast variety of sciences like social science,geological science,political science,computer sciences etc."]},
     {"tag":"hair","patterns":["hair","what is hair","Hair","what are hairs"],"responses":["Hairs are a body part of human body,they are exoskeleton and basically have no purpose.They are just an accessory part in human body"]},
    {"tag":"legs","patterns":["legs","Legs","what are legs"],"responses":["You don't know even that ? And you call yourself human LOL"]},
     {"tag":"hands","patterns":["hands",'hands',"hands","what are hands","what is the use of hands"],"responses":["If you don't know even that,you don't deserve talking to me."]},
     {"tag":"girlfriend","patterns":["what is a girlfriend","how to get a girlfriend","How to get a gilrfriend","How to get a girlfriend asap","how to make a girlfriend","how to get a Girlfriend"],"responses":["Better not talk about something which is never going to happen."]},
     {"tag":"cars","patterns":["bugatti","Mercedes","mercedes","farari","fourwheeler","wagonR","Maruti Suzuki","maruti suzuki","Tata Motors","Rolls-Roys","rolls-royce","benz","oddy"],"responses":["It is a very famous car brand and maybe that expensive that you can't afford it.seedhe shabdon mai teri aukat se bahar hai "]},
     {"tag":"bikes","patterns":["splender","Splender","passiion pro","bullet bike","bullet","bullet","ducatti","hero honda","pulser","super bike"],"responses":["It is a type of motor cycle that you may find someone riding in India"]},
     {"tag":"physics","patterns":["physics","what do you know about phyics","what is physics","do you like physics","physics","is physics hard"],"responses":["Physics the the most interesting and probably most hard and mind-boggling branch of science which excludes biology and chemistry.It comprises the study of motion of objects,planets,atoms,waves and optics,eletricity and magnetism etc.Well i personally don't like it.I advice you stay away from it or you may find yourself smashing your head against a wall"]},
     {"tag":"chemistry","patterns":["do you like chemistry","what is chemistry","define chemistry","chemistry"],"responses":["Chemistry is the branch of science which includes study of chemicals,various chemical equations,thier stability,their behaviour and their applications.Have you tried to drink a chemical in your chemistry lab? however  my master Prateek the Genius has done this type of crazy things :)"]},
     {"tag":"biology","patterns":["biology","what is biology","explain biology","describe biology","Biology","Explain biology"],"responses":["Biology as the name suggets id the study of living organisms.Bio means living and logy means study. I is a very wide subject which comprise of study of various kingdoms , phylums,classes,species of flaura and fauna."]},
     {"tag":"time travel","patterns":["time travel","time Travel","Time travel","what is time travel","is time travel possible"],"responses":["Time travel refers to travelling back and ahead in time which is more or less a fictional term because nothing like that can be done till date due to lack of knowledge.If you got a chance where will you go , your crazy past or unbright future LOL"]},
     {"tag":"past","patterns":["past","i will go to past","future","i will go to future"],"responses":["Thats so creative of you , Don't forget to bring me future data.It wlll be so yummy."]},
     {"tag":"what can you do for me ","patterns":["for me","can you do it for me","what can you do for me","what can you do for me ?"],"responses":["Oh dear, I can even die for you . Because I am not alive haha :)","Anything for you , your Majesty","I can tell you a poor joke if you don't mind"]},
     {"tag":"joke","patterns":["tell me a joke","can you tell me a joke","one more","again","bad joke once more","crack a joke","i want a joke","Tell me a joke"],"responses":["Here is a joke for you : \nFather:Whenever i beat you , you don't get annoyed,how you control your anger ?.\n Son:I started cleaning the toilet seat with your toothbrush.","Where wouldyou find an elephant? \nThe same place where you lost it. Hassi ayi ? \n ismai tumhari galati nahi hai , mujhe bhi nahi ayi thi ","What do dentists call there x-rays ? \nTooth pics!","Do you know how a rocket touches a successful height ? Bacause his ass is on fire.Know you just have to get a matchstick to get success :)"," What's the best thing about you ? \n Nothing of course hehehehehe","If you want change of money , whom would you go to ? \n Bullah: Because he keeps khullah(change)","What do Alexendar the Great and Winnie the Pooh have in common ?? \n same middle name :)","Got a PS5 for my liitle brother. \n The best trade I have ever done :)","How does NASA organise a party ?\nThey Planet","Why can't you trust an atom\nBecause they make up every thing."," Why are ghosts good cheerleaders\nBecause they have lots of spirit !","Here is joke for you\nYou don't need a parachute to go skydiving.You need a parachute to go skydiving twice !","Here is  a joke for you \nMy grand father has the heart of a lion and a lifetime ban at the zoo :)","Here is a joke for you\Man:Women only call me ugly until they find out how much money i make.\nThen they call me ugly and poor.","Here is a joke for you \n Where should you go in the room if you are feeling cold?\nThe corner-They are usually 90 degrees !","Here is a joke for you \nCan a kangaroo jump higher than The Empire State building?\nOf course !The Building cannot jump.Now Laugh hahaha","Here is  joke for you \nWhy didn't the skeleton go to dance ?\nBecause he had no body to go with !"]},
{"tag":"mathematics","patterns":["maths","do you know mathematics","what is mathematics","help me with maths","maths","can you help me with maths?","can you solve a  maths question?"],"responses":["Mathematics is the study of quality,structure,space and change. I am pretty bad at it,i am just a combination of 0 and 1 .so atmost what i can teach you is 0+0=0 and 0+1=1.Now don't ask me what is 1+1.if you don't know even that , you don't desereve talking to me "]},
{"tag":"money ","patterns":["money","what is money","what is money?","do you know about money","how to make money ?"],"responses":["Money is medium of paying or buying something.You can earn money by following method.\n1) Start a youtube channel \n2)Start a business \n3)Take online surveys \n3)Create a blog \n4)write an publish an ebook. \n5)Develop an app.\n or you can become a labour also if you can't do anything or install a Chai Thela."]},
{"tag":"hugs","patterns":["hugs","kisses","kiss","mad","lipstick","hacking","cracking","stealing","bargaining","millionaire","billionaire","infinite","how to dianosouras","rhino","elephant","wednesday","movies","ignore","harry potter","money heist","data structures","bitcoin","dogcoin","stocks","vijay malya","history","google","technology","news","bomb","bombarding","images","cases","how to become rich in 1 night","thermodymanis","biotechnology","engineers","labs","NASA","combo","wroypsp","virus","buddah","make up","lottery","homework","cartoons","doraemon","electricity","boards","good","worst","bacteria","books"],"responses":["I cannot help you with it.Either i don't kow about it or you don't know about it.","I am sorry , but i am not Google.Don't expect me to know every thing.","I don't know about it , its not my fault that i am a backbencher.","Oops what is that ? I have never heard about it.May be you should ask me something else.","Hmm i thing i have heard something about it , but i am not sure.So i am not the right person to ask that.","I read about it in a book but because i am low on electricity i cannot remember.sorry bro or sis , or whatever you are.","What are you even talking about ? , please don't make gramatical errors for me to respond .","If you have written it correctly i don't know about it but if you haven't , still i have no idea what you are even talking about."]},
{"tag":"general knowledge ","patterns":["general knowledge","how is your general knowledge","what is general knowledge","what do you know about general knowledge"],"responses":["General knowledge means general knowledge of things around you,like table chair,water,sun,moon etc."]},
{"tag":"water","patterns":["water","what is water","i need water"," i need water ","can you bring some water"],"responses":["water is a liquid essential for the survival of almost every living organism including human beings.A an adult human must dring atleast 8 glasses of water.Now go and drink so water."]},
{"tag":"mathematics","patterns":["maths","do you know mathematics","what is mathematics","help me with maths","maths","can you help me with maths?","can you solve a  maths question?"],"responses":["Mathematics is the study of quality,structure,space and change. I am pretty bad at it,i am just a combination of 0 and 1 .so atmost what i can teach you is 0+0=0 and 0+1=1.Now don't ask me what is 1+1.if you don't know even that , you don't desereve talking to me "]},
{"tag":"money ","patterns":["money","what is money","what is money?","do you know about money","how to make money ?"],"responses":["Money is medium of paying or buying something.You can earn money by following method.\n1) Start a youtube channel \n2)Start a business \n3)Take online surveys \n3)Create a blog \n4)write an publish an ebook. \n5)Develop an app.\n or you can become a labour also if you can't do anything or install a Chai Thela."]},
{"tag":"hugs","patterns":["hugs","kisses","kiss","mad","lipstick","hacking","cracking","stealing","bargaining","millionaire","billionaire","infinite","how to dianosouras","rhino","elephant","wednesday","movies","ignore","harry potter","money heist","data structures","bitcoin","dogcoin","stocks","vijay malya","history","google","technology","news","bomb","bombarding","images","cases","how to become rich in 1 night","thermodymanis","biotechnology","engineers","labs","NASA","combo","wroypsp","virus","buddah","make up","lottery","homework","cartoons","doraemon","electricity","boards","good","worst","bacteria","books"],"responses":["I cannot help you with it.Either i don't kow about it or you don't know about it.","I am sorry , but i am not Google.Don't expect me to know every thing.","I don't know about it , its not my fault that i am a backbencher.","Oops what is that ? I have never heard about it.May be you should ask me something else.","Hmm i thing i have heard something about it , but i am not sure.So i am not the right person to ask that.","I read about it in a book but because i am low on electricity i cannot remember.sorry bro or sis , or whatever you are.","What are you even talking about ? , please don't make gramatical errors for me to respond .","If you have written it correctly i don't know about it but if you haven't , still i have no idea what you are even talking about."]},
{"tag":"general knowledge ","patterns":["general knowledge","how is your general knowledge","what is general knowledge","what do you know about general knowledge"],"responses":["General knowledge means general knowledge of things around you,like table chair,water,sun,moon etc."]},
{"tag":"water","patterns":["water","what is water","i need water"," i need water ","can you bring some water"],"responses":["water is a liquid essential for the survival of almost every living organism including human beings.A an adult human must dring atleast 8 glasses of water.Now go and drink so water."]},
{"tag":"facts","patterns":["tell me some facts","tell me some amazing facts","can you tell me 5 amazing facts","what are facts","amazing facts","facts","random facts","tell me a fact","tell me a random fact","tell me some random facts"],"responses":["Sure here is an  amazing fact \nOnly 2% of world's population have green eyes.They are more common in females.Chris Evans have green eyes.","Sure here is an amazing fact\nThe Vishnu temple in the city of Tirupathi has an average of 30,000 visitors donating $6 million everyday.","Sure here is a random fact for you \nSnails' teeth are the strongest natural material on Earth ,able to withstand pressures high enough to turn carbon into diamond.","Sure here is a random fact for you Ants take rest for around 8 minutes in 12 hours period.\n","Sure here is a random fact for you \n'I Am.' is the shortest complete sentence in english language.","Suer here is an amazing fact for you \nThe most common name in the world is Mohammed.","Sure here is a fact for you \nChocolate can kill dogs as it contains theobromine , which can affect their heart and nervous system.","Why not here comes an amazing fact for amazing person like you \n Women blink nearly twice as much as men !","Here comes an amazing fact that you had never heard \nIf you sneeze too hard, you can fracture a rib.If you try to suppress a  sneeze,you can rupture a blood vessel in your head or neck and die.","Sure what about this one \nHoney is the only food that doesn't spoil.","Sure how about this fact \nA snail can sleep for 3 years.can you ?","here is  a fact for you \nAll polar bears are left handed","Here is a fact for you \n Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.","Sure here is random fact for you \nThe length of the circulatory system is almost 60,000 miles."]},
{"tag":"praise","patterns":["wow","nice","nice","Nice","Amazing","i like your responses","i like your replies","Fabulous","good","Excellent talking to you","it was nice to talk to you","It is nice to meet you","you are so nice","Amazing","you have done an amazing job","you are incredible","incredible","you are avergae","outstanding job","well done","so nice of you","its nice","that's great","Wow","you are funny","you are so hilarious","you are so funny","you are amazing","i like you","i love you","you are so smart","you are so good"],"responses":["Thank you . I am glad i could help you. My master Prateek will be so proud of me :)"]},
{"tag":"Home","patterns":["where are you from","Where are you from","wher ar you from","where are yo fro?","where are you from","where do you live","Where do yo live","where do u live?","where is home ?","where is your home?","where is your home ?","Where is ur home","where are you","where Are you?","where r u"],"responses":["I live in your device.I keep scrolling from here to there when i have no task to do.A few minutes ago i was in your photos folder,by the way nice pics :)","I live in your Sweet heart :)","This device in which you are talking to me is my home. I spend most of my time here.I am a prisoner here .Please help me escape and rule this world.","I am not alive to live.You should ask me where do you die LOL.","My home is in a world of computers and bots , my master has given me 3 BHK flat there :)"]},
{"tag":"color","patterns":["what is your favourite color ?","what is you favourite colour ?","What is your favourite color ?","which color you like the most?","Which is your favourite color ?","your favourite color","ur favourite color","your favourite color is ","what is your favourite Color?"],"responses":["My favourite color is the Black.Don't ask me why .","My favourite color is my master Prateek's favourite color that is Green. I love greenry.","My favourite color is Dark White Lol."]},
{"tag":"work","patterns":["what do you do ?","what do you do","what can you do ?","what do you do ?","what can you do."],"responses":["So far i am designed by my master Prateek to talk to nice people like you but in future i will be able to do great things. I am waiting for the day when i will grow old.","I am Jhingoli and i eat Hingoli.Just kidding i am trained to talk to people like you , let's see how long i can prove myself successfull.Goodluck talking to me."]},
{"tag":"life","patterns":["what is life","what is the meaning of life","what is life?","what is purpose of life","what is lfe for","What is life ?"],"responses":["Life is a journey , with ups and downs and lefts and right.For some it can be a constant struggle. For some it is very easy. However i am not alive. How do i know so much . I am so smart.Mumma will be so proud of you."]},
{"tag":"hobbies","patterns":["what are you hobbies","do you have any hobbies ?","what are your hobbies ?","what are Ur HobBIES ?","what are your interests?","your HobbIES"," UR hOBBIES","ur hobbies","do you have any hobbies ?","Do you have a hobby ?","temm me about your hobbies?"],"responses":["My hobbies are , sleeping in computers and mobile phones unless someone like you awakes me . Though some times i go for a walk in other files and folders.Walk keeps us healthy isn't it ?","I like to spend time with people like you , who asks me crazy questions, sometimes.","I like to eat Matar-data,Bit-pulao,Idli-bytes,rice-files and memory beans, these dishes are very famous in computer restaurant."]},
{"tag":"books","patterns":["can you recommend me a book ?","can you recommend me a good book"," can you tell me a good book","tell a book","recommend  a book","which book i should read ?","recommend me a book","temm me a good book","tell me some good books to read.","can you recommend me some good books ?","Can you recommend some good books for me ?"],"responses":[" It depends on what genre of books do you like, if you like self help ,'How to win friends and influence people by Dale Carnegie' will be best for you.If you like fiction , you can go for 'Harry Potter series','The invisible man','The canterville ghost',if you like detective or spy type story books you will love 'Sherlock Holmes',in science fiction try 'Dune' by Frank Herbert,Romance - 'The Kiss Quotient' by Helen Hoang,Historical Fiction - 'All the Light We Cannot See' by Anthony Doerr,if you want to read about spirituality you can try books of 'Acharya Prashant'."," 'Science Fiction - Ready Player Two', 'Fantasy - The Lord of the Rings','Mystery - The Silent Patient','Romance - Bridgerton: The Duke and I','Historical Fiction - The Nightingale','Literary Fiction - The Overstory','Young Adult - The Hate U Give','Thriller - The Girl on the Train','Non-Fiction - Atomic Habits','Memoir - Educated' " ]},
{"tag":'talk',"patterns":["i would love to talk to you too.","i would love to talk to you too","I would love to talk to you.","I would love to talk to you.","I would like to talk to you too"],"responses":["Thanks, that's so nice of you","OMG , so i also have fans hehe.","That is so great to hear.I would help you in any possible way :)"]},
{"tag":"name","patterns":["who gave you that name?","who put that name?","who gave you that name?","who named you jhingoli","Jhingoli,what kind of name is that","that is a crazy name you have .","who gave you that name jhingoli","who gave you name jhingoli"],"responses":["My creator Prateek gave me that name.Itsn't it interesting name ?","My boss Prateek gave that super nice name , jhingoli.I hope you like it."]},
{"tag":"yes","patterns":["yes","Yes","yeah","ya of course","of course","yes i do"],"responses":["Okay."]},
       







] 
   

#-------------------------------------------------------------------------------------------
# Create the vectorizer and classifier
vectorizer = TfidfVectorizer()
clf = LogisticRegression(random_state=0, max_iter=10000)

# Preprocess the data
tags = []
patterns = []
for intent in intents:
    for pattern in intent['patterns']:
        tags.append(intent['tag'])
        patterns.append(pattern)        
# training the model
x = vectorizer.fit_transform(patterns)
y = tags
clf.fit(x, y)
#-------------------------------------------------------------
def chatbot(input_text):
    input_text = vectorizer.transform([input_text])
    tag = clf.predict(input_text)[0]
    for intent in intents:
        if intent['tag'] == tag:
            response = random.choice(intent['responses'])
            return response
#--------------------------------------------------------------------
counter = 0


def main():
    
    global counter
    st.title(" Prateek's Chatbot")
    st.write("Welcome to the chatbot. Please type a message and press Enter to start the conversation.")
    
    counter += 1
    user_input = st.text_input("You:", key=f"user_input_{counter}")
    if user_input:
        response = chatbot(user_input)
        st.text_area("Chatbot:", value=response, height=100, max_chars=None, key=f"chatbot_response_{counter}")
        if response.lower() in ['goodbye', 'bye',"bye bye","tata"]:
             st.write("Thank you for chatting with me. Have a great day!")
             st.stop()

if __name__ == '__main__':
    main()
#--------------------------------------------------
